language: ruby

rvm:
- 2.4.0

notifications:
  slack:
    secure: JTJZsM5ecL9kAgSXicHwZRdTWH+rV9P3Di7ooSgOHRQ6PLaANZ1mZXsknzF5K4Km5UFU+Dpa+fYr9Mv6JZcicGhmswiQQMu0wj0oPaJh1R2t1jORMKg89YsJ/4VE4B1R+JF/UOUti/gXS3/0rc7hGdbIA3lpoCRNNaXuroXboVcSVx/m09og+Me8tTfkSoP//xFj+Tq7Gs7q+F0Z9UeuqLQ8VnKx59MlbbCZm6U6PWx/AHAhq4KoKBxtT1+BtfspIV4RJ+ssgfOrlU7S8XgmTBkOh/pLHh8srIOwQBHF9NN9JPq2wyEiK6JOPN+AHEwZE3YZ3PsSD0UAJ20Kx9mgt8yrpMZ33m0IN6wG7l27SP1eNtUoTGYO9IFmnDQddQyChdt4SirLaxhFEriIi2Cdcioc0PtWnWN9iWh4ryL35GnI1bzhzNY2rAv/dhMPxpxS04fu9u6ZhCkHzm5cmtelTKWN5aakCjvQ+CsZDMTLf5HMPJE7S4SzWXoliDUE4cjLM6TpSDsYv8ndu//sFRcjwHtUnQotNL68hBvIvQRNzNsBBb+NQsy3Dikuhf0iVyCZI6XqpFREblh9VrJdPh/7KWkagCKhvyWVajPOY+YJrVmD1xtalO5XdCHdqrtiySOodwDM8uH8sGKeZHfWi3G/qQxbrbMePL4xZ6RCX6cCpic=
    on_success: change
    on_failure: always
  email: false
